# Generated by Django 5.1 on 2024-09-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_remove_event_end_time_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
