# Generated by Django 4.2.11 on 2024-09-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('week_number', models.IntegerField(default=38)),
                ('work_start_morning', models.TimeField(blank=True, null=True)),
                ('work_end_morning', models.TimeField(blank=True, null=True)),
                ('work_start_afternoon', models.TimeField(blank=True, null=True)),
                ('work_end_afternoon', models.TimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intern')),
            ],
        ),
    ]
