# Generated by Django 5.1.1 on 2024-09-16 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_alter_intern_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='arrival',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='intern',
            name='departure',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
