# Generated by Django 4.2.11 on 2024-09-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_alter_intern_days_off_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='phone',
        ),
    ]
