# Generated by Django 4.2.11 on 2024-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_remove_intern_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='days_off_left',
            field=models.FloatField(default=25),
        ),
    ]
