# Generated by Django 4.2.11 on 2024-09-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Initial request', max_length=200)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('duration', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('comment_staff', models.CharField(default='', max_length=200)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intern')),
            ],
        ),
    ]
