# Generated by Django 4.2.11 on 2024-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_event_half_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='half_day',
            new_name='is_half',
        ),
    ]
