# Generated by Django 4.2.11 on 2024-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_rename_half_day_event_is_half'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_half',
        ),
        migrations.AddField(
            model_name='event',
            name='half_day',
            field=models.IntegerField(default=0),
        ),
    ]
