# Generated by Django 4.2.11 on 2024-09-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_event_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='half_day',
            new_name='duration',
        ),
    ]
