# Generated by Django 4.2.11 on 2024-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_rename_half_day_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment_staff',
            field=models.CharField(default='', max_length=200),
        ),
    ]
