# Generated by Django 4.2.11 on 2024-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_event_comment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
