# Generated by Django 4.2.11 on 2024-09-18 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_remove_event_is_approved_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
